### PR TITLE
Coin info section

### PR DESCRIPTION
**Pull request by Nikolaj-K**
Turns the Exchange section into a Coin section of which Exchange is a subsection. 
Adds a summary with basic plaintext token info so one can link to it.

### CODE REVIEW

**Comment by Nikolaj-K** [comment]
I just saw that there's a blank character in the first plaintext line.
Not sure if this is originally intended, but I'd adhered to it.

Eventually I think that not the whole table of content of the official doc need to be represented in the Awesome as separate section. (But maybe it naturally wanders into a separate file once there's more project to report of in the Awesome list)

**Comment by Nikolaj-K** [comment]
Someone corrected my on not using "token" BIND, but fyi I now see the use here too
https://github.com/Bx64/Awesome-Compendia/blob/master/awesome-blog/CompendiaCommunityFund_Proposal.md

Maybe I'll push a change in that file too

**Comment by Bx64** [comment]
Changes approved:
- awesome-blog/CompendiaCommunityFund_Proposal.md
- awesome-blog/Staking.md

Changes not (yet) approved:
- README.md

Alphabetical order is not something that we are willing to change, and therefore should be adhered to. Once the list grows, not having items in alphabetical orders will make the list impractical and completely unusable. 
The table of contents may be changed later, but for now - with the amount of submissions - it is better off complete.

Regarding exchanges: if we are changing this section, it is better to make a distinction between BIND and wBIND markets. It does not look like Altilly is returning anytime soon, so that can be removed. Therefore please apply the following subsections:
- Exchanges
    - BIND
        - No active market currently.
    - wBIND
        - BIND.exchange (Uniswap)
        - Switcheo

We are still discussing the section name and will get back to this later.

**Comment by Nikolaj-K** [comment]
kk, I mean it's just a block of text so one can link Telegram people somewhere. It seem I don't really have an incentive to enter into a do-this-do-that relationship here so if you figured out how you like your list, I'd say just merge this in as is and make the changes on top of it.

**Comment by Bx64** [comment]
We have guidelines for the format we are using and if you see getting feedback on your suggested changes as a 'do-this-do-that relationship', than I'm not sure open source project commits are a great idea.

Feel free to add the feedback, otherwise we will take your suggestions, review them and rework them how we see fit with our next update.

**Comment by Nikolaj-K** [comment]
Yeah that's what I mean, just take it as base for a restructuring of how you see it fit.

**Pull request closed without merging**
